### PR TITLE
New Navigation (Top bar + Header)

### PR DESCRIPTION
**Pull request by hugomarquesdev**
#307

### CODE REVIEW

**Review by obernardovieira — APPROVED** [review]
Menus editable through prismic, right?

**Comment by hugomarquesdev** [comment]
> Menus editable through prismic, right? @obernardovieira 
every single thing that I'm working on the website is always customizable on prismic if possible. so, yeah

**Comment by obernardovieira** [comment]
can we merge?

**Comment by hugomarquesdev** [comment]
> can we merge?

its ok to me 👌

**Review by PauloSousapt — APPROVED** [review]

**Pull request merged**
